/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 4.8.6
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <../QCustomPlot/qcustomplot.h>
#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QComboBox>
#include <QtGui/QFrame>
#include <QtGui/QHBoxLayout>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QMainWindow>
#include <QtGui/QPushButton>
#include <QtGui/QSpacerItem>
#include <QtGui/QTabWidget>
#include <QtGui/QTableWidget>
#include <QtGui/QVBoxLayout>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QFrame *frame_2;
    QTabWidget *tabWidget;
    QWidget *tab;
    QFrame *filteredWeightFrame;
    QLabel *lblProductWeight;
    QLabel *lblWeightHeader;
    QFrame *descriptionFrame;
    QLabel *lblDescription;
    QLabel *lblDescription_2;
    QFrame *rawWeightFrame;
    QLabel *lblRawWeight;
    QLabel *lblRawWeight_2;
    QFrame *batchFrame;
    QLabel *lblBatchID;
    QLabel *lblBatch;
    QFrame *serialFrame;
    QLabel *lblSerialNumber;
    QLabel *lblSerial;
    QFrame *productIDFrame;
    QLabel *lblProductID;
    QLabel *lblproduct;
    QFrame *recipeFrame;
    QLabel *lblRecipeID;
    QLabel *lblRecipe;
    QFrame *lengthFrame;
    QLabel *lblLength;
    QLabel *lblLength_2;
    QFrame *confidenceFrame;
    QLabel *lblWeightConfidence;
    QLabel *lblConfidence;
    QFrame *destinationFrame;
    QLabel *lblDestinationGate;
    QLabel *lblDestination;
    QPushButton *btnNetWeightConnect;
    QPushButton *btnDisconnect;
    QWidget *tab_2;
    QFrame *destinationFrame_2;
    QLabel *lblDestinationGate_2;
    QLabel *lblDestination_2;
    QFrame *serialFrame_2;
    QLabel *lblSerialNumber_2;
    QLabel *lblSerial_2;
    QFrame *filteredWeightFrame_2;
    QLabel *lblProductWeight_2;
    QLabel *lblWeightHeader_2;
    QFrame *batchFrame_2;
    QLabel *lblBatchID_2;
    QLabel *lblBatch_2;
    QFrame *FrameGateBufferStatus;
    QCheckBox *cbxGate1;
    QCheckBox *cbxGate2;
    QCheckBox *cbxGate3;
    QCheckBox *cbxGate4;
    QCheckBox *cbxGate5;
    QCheckBox *cbxGate6;
    QLabel *lblGateStatus;
    QFrame *FrameBufferWeight;
    QLabel *lblBWgt1;
    QLabel *lblBWgt2;
    QLabel *lblBWgt3;
    QLabel *lblBWgt4;
    QLabel *lblBWgt5;
    QLabel *lblBWgt6;
    QLabel *lblBWgt;
    QFrame *FrameBufferCount;
    QLabel *lblBCnt1;
    QLabel *lblBCnt2;
    QLabel *lblBCnt3;
    QLabel *lblBCnt4;
    QLabel *lblBCnt5;
    QLabel *lblBCnt6;
    QLabel *lblBCnt;
    QPushButton *btnCloseBatch;
    QWidget *tabGraph;
    QVBoxLayout *verticalLayout;
    QWidget *widget;
    QFrame *frame_4;
    QCustomPlot *customPlot;
    QLabel *lblFilteredWeight;
    QPushButton *btnForward;
    QPushButton *btnReverse;
    QLabel *lblElementId;
    QPushButton *ymax;
    QPushButton *ymin;
    QPushButton *xmin;
    QPushButton *xmax;
    QWidget *tabSettings;
    QComboBox *cbSettingsMenu;
    QPushButton *btnRefreshSettingsList;
    QTableWidget *settingsTable;
    QWidget *tabRecipe;
    QPushButton *btnRefreshRecipeList;
    QComboBox *cbRecipeMenu;
    QTableWidget *recipeTable;
    QWidget *tabDio;
    QWidget *layoutWidget_1;
    QHBoxLayout *horizontalLayout_3;
    QCheckBox *chkDIN_03;
    QSpacerItem *horizontalSpacer_5;
    QLabel *label_6;
    QLabel *lblDIN_03;
    QSpacerItem *horizontalSpacer_6;
    QLabel *label_7;
    QLabel *lblDOUT_03;
    QWidget *layoutWidget_2;
    QHBoxLayout *horizontalLayout_4;
    QCheckBox *chkDIN_04;
    QSpacerItem *horizontalSpacer_7;
    QLabel *label_8;
    QLabel *lblDIN_04;
    QSpacerItem *horizontalSpacer_8;
    QLabel *label_9;
    QLabel *lblDOUT_04;
    QWidget *layoutWidget_3;
    QHBoxLayout *horizontalLayout;
    QCheckBox *chkDIN_01;
    QSpacerItem *horizontalSpacer;
    QLabel *label_2;
    QLabel *lblDIN_01;
    QSpacerItem *horizontalSpacer_2;
    QLabel *label_4;
    QLabel *lblDOUT_01;
    QWidget *layoutWidget_4;
    QHBoxLayout *horizontalLayout_2;
    QCheckBox *chkDIN_02;
    QSpacerItem *horizontalSpacer_3;
    QLabel *label_3;
    QLabel *lblDIN_02;
    QSpacerItem *horizontalSpacer_4;
    QLabel *label_5;
    QLabel *lblDOUT_02;
    QFrame *transmitFrame;
    QPushButton *btnCalibrateZERO;
    QPushButton *btnCalibrateWEIGHT;
    QLabel *label;
    QCheckBox *chkWriteToLoadcell;
    QCheckBox *chkDebugWriteToFile;
    QFrame *frameState;
    QLabel *lblSystemState;
    QLabel *lblCountDown;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(800, 600);
        QPalette palette;
        QBrush brush(QColor(115, 115, 115, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush);
        palette.setBrush(QPalette::Active, QPalette::Window, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush);
        MainWindow->setPalette(palette);
        MainWindow->setStyleSheet(QString::fromUtf8("background-color: rgb(115, 115, 115);"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        frame_2 = new QFrame(centralWidget);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(110, 30, 661, 531));
        frame_2->setStyleSheet(QString::fromUtf8("background-color: rgb(100, 135, 223);"));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        tabWidget = new QTabWidget(frame_2);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setEnabled(true);
        tabWidget->setGeometry(QRect(20, 30, 621, 411));
        QSizePolicy sizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(tabWidget->sizePolicy().hasHeightForWidth());
        tabWidget->setSizePolicy(sizePolicy);
        QFont font;
        font.setPointSize(14);
        font.setBold(false);
        font.setWeight(50);
        tabWidget->setFont(font);
        tabWidget->setFocusPolicy(Qt::ClickFocus);
        tabWidget->setLayoutDirection(Qt::LeftToRight);
        tabWidget->setAutoFillBackground(false);
        tabWidget->setStyleSheet(QString::fromUtf8("QScrollBar:vertical {min-width: 50px; margin-right: 20px;}"));
        tabWidget->setTabPosition(QTabWidget::North);
        tabWidget->setTabShape(QTabWidget::Rounded);
        tabWidget->setIconSize(QSize(16, 16));
        tabWidget->setElideMode(Qt::ElideNone);
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        filteredWeightFrame = new QFrame(tab);
        filteredWeightFrame->setObjectName(QString::fromUtf8("filteredWeightFrame"));
        filteredWeightFrame->setGeometry(QRect(250, 190, 231, 151));
        filteredWeightFrame->setStyleSheet(QString::fromUtf8(""));
        filteredWeightFrame->setFrameShape(QFrame::StyledPanel);
        filteredWeightFrame->setFrameShadow(QFrame::Raised);
        lblProductWeight = new QLabel(filteredWeightFrame);
        lblProductWeight->setObjectName(QString::fromUtf8("lblProductWeight"));
        lblProductWeight->setGeometry(QRect(40, 30, 151, 31));
        QFont font1;
        font1.setPointSize(20);
        font1.setBold(true);
        font1.setWeight(75);
        lblProductWeight->setFont(font1);
        lblProductWeight->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblWeightHeader = new QLabel(filteredWeightFrame);
        lblWeightHeader->setObjectName(QString::fromUtf8("lblWeightHeader"));
        lblWeightHeader->setGeometry(QRect(6, 0, 91, 21));
        descriptionFrame = new QFrame(tab);
        descriptionFrame->setObjectName(QString::fromUtf8("descriptionFrame"));
        descriptionFrame->setGeometry(QRect(250, 20, 351, 151));
        descriptionFrame->setStyleSheet(QString::fromUtf8(""));
        descriptionFrame->setFrameShape(QFrame::StyledPanel);
        descriptionFrame->setFrameShadow(QFrame::Raised);
        lblDescription = new QLabel(descriptionFrame);
        lblDescription->setObjectName(QString::fromUtf8("lblDescription"));
        lblDescription->setGeometry(QRect(10, 20, 321, 111));
        QFont font2;
        font2.setPointSize(9);
        font2.setBold(true);
        font2.setWeight(75);
        lblDescription->setFont(font2);
        lblDescription->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblDescription->setWordWrap(true);
        lblDescription_2 = new QLabel(descriptionFrame);
        lblDescription_2->setObjectName(QString::fromUtf8("lblDescription_2"));
        lblDescription_2->setGeometry(QRect(10, 0, 81, 21));
        rawWeightFrame = new QFrame(tab);
        rawWeightFrame->setObjectName(QString::fromUtf8("rawWeightFrame"));
        rawWeightFrame->setGeometry(QRect(130, 190, 111, 71));
        rawWeightFrame->setStyleSheet(QString::fromUtf8(""));
        rawWeightFrame->setFrameShape(QFrame::StyledPanel);
        rawWeightFrame->setFrameShadow(QFrame::Raised);
        lblRawWeight = new QLabel(rawWeightFrame);
        lblRawWeight->setObjectName(QString::fromUtf8("lblRawWeight"));
        lblRawWeight->setGeometry(QRect(20, 30, 71, 31));
        QFont font3;
        font3.setPointSize(16);
        font3.setBold(true);
        font3.setWeight(75);
        lblRawWeight->setFont(font3);
        lblRawWeight->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblRawWeight_2 = new QLabel(rawWeightFrame);
        lblRawWeight_2->setObjectName(QString::fromUtf8("lblRawWeight_2"));
        lblRawWeight_2->setGeometry(QRect(10, 0, 81, 21));
        batchFrame = new QFrame(tab);
        batchFrame->setObjectName(QString::fromUtf8("batchFrame"));
        batchFrame->setGeometry(QRect(10, 100, 111, 71));
        batchFrame->setStyleSheet(QString::fromUtf8(""));
        batchFrame->setFrameShape(QFrame::StyledPanel);
        batchFrame->setFrameShadow(QFrame::Raised);
        lblBatchID = new QLabel(batchFrame);
        lblBatchID->setObjectName(QString::fromUtf8("lblBatchID"));
        lblBatchID->setGeometry(QRect(10, 30, 91, 31));
        QFont font4;
        font4.setPointSize(12);
        font4.setBold(true);
        font4.setWeight(75);
        lblBatchID->setFont(font4);
        lblBatchID->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblBatch = new QLabel(batchFrame);
        lblBatch->setObjectName(QString::fromUtf8("lblBatch"));
        lblBatch->setGeometry(QRect(10, 0, 81, 21));
        serialFrame = new QFrame(tab);
        serialFrame->setObjectName(QString::fromUtf8("serialFrame"));
        serialFrame->setGeometry(QRect(130, 100, 111, 71));
        serialFrame->setStyleSheet(QString::fromUtf8(""));
        serialFrame->setFrameShape(QFrame::StyledPanel);
        serialFrame->setFrameShadow(QFrame::Raised);
        lblSerialNumber = new QLabel(serialFrame);
        lblSerialNumber->setObjectName(QString::fromUtf8("lblSerialNumber"));
        lblSerialNumber->setGeometry(QRect(20, 30, 81, 31));
        lblSerialNumber->setFont(font3);
        lblSerialNumber->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblSerial = new QLabel(serialFrame);
        lblSerial->setObjectName(QString::fromUtf8("lblSerial"));
        lblSerial->setGeometry(QRect(10, 0, 81, 21));
        productIDFrame = new QFrame(tab);
        productIDFrame->setObjectName(QString::fromUtf8("productIDFrame"));
        productIDFrame->setGeometry(QRect(130, 20, 111, 71));
        productIDFrame->setStyleSheet(QString::fromUtf8(""));
        productIDFrame->setFrameShape(QFrame::StyledPanel);
        productIDFrame->setFrameShadow(QFrame::Raised);
        lblProductID = new QLabel(productIDFrame);
        lblProductID->setObjectName(QString::fromUtf8("lblProductID"));
        lblProductID->setGeometry(QRect(10, 30, 91, 31));
        lblProductID->setFont(font4);
        lblProductID->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblproduct = new QLabel(productIDFrame);
        lblproduct->setObjectName(QString::fromUtf8("lblproduct"));
        lblproduct->setGeometry(QRect(10, 0, 81, 21));
        recipeFrame = new QFrame(tab);
        recipeFrame->setObjectName(QString::fromUtf8("recipeFrame"));
        recipeFrame->setGeometry(QRect(10, 20, 111, 71));
        recipeFrame->setStyleSheet(QString::fromUtf8(""));
        recipeFrame->setFrameShape(QFrame::StyledPanel);
        recipeFrame->setFrameShadow(QFrame::Raised);
        lblRecipeID = new QLabel(recipeFrame);
        lblRecipeID->setObjectName(QString::fromUtf8("lblRecipeID"));
        lblRecipeID->setGeometry(QRect(10, 30, 91, 31));
        lblRecipeID->setFont(font4);
        lblRecipeID->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblRecipe = new QLabel(recipeFrame);
        lblRecipe->setObjectName(QString::fromUtf8("lblRecipe"));
        lblRecipe->setGeometry(QRect(10, 0, 81, 21));
        lengthFrame = new QFrame(tab);
        lengthFrame->setObjectName(QString::fromUtf8("lengthFrame"));
        lengthFrame->setGeometry(QRect(10, 190, 111, 71));
        lengthFrame->setStyleSheet(QString::fromUtf8(""));
        lengthFrame->setFrameShape(QFrame::StyledPanel);
        lengthFrame->setFrameShadow(QFrame::Raised);
        lblLength = new QLabel(lengthFrame);
        lblLength->setObjectName(QString::fromUtf8("lblLength"));
        lblLength->setGeometry(QRect(20, 30, 71, 31));
        lblLength->setFont(font3);
        lblLength->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblLength_2 = new QLabel(lengthFrame);
        lblLength_2->setObjectName(QString::fromUtf8("lblLength_2"));
        lblLength_2->setGeometry(QRect(10, 0, 81, 21));
        confidenceFrame = new QFrame(tab);
        confidenceFrame->setObjectName(QString::fromUtf8("confidenceFrame"));
        confidenceFrame->setGeometry(QRect(490, 190, 111, 71));
        confidenceFrame->setStyleSheet(QString::fromUtf8(""));
        confidenceFrame->setFrameShape(QFrame::StyledPanel);
        confidenceFrame->setFrameShadow(QFrame::Raised);
        lblWeightConfidence = new QLabel(confidenceFrame);
        lblWeightConfidence->setObjectName(QString::fromUtf8("lblWeightConfidence"));
        lblWeightConfidence->setGeometry(QRect(30, 30, 61, 31));
        lblWeightConfidence->setFont(font3);
        lblWeightConfidence->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblConfidence = new QLabel(confidenceFrame);
        lblConfidence->setObjectName(QString::fromUtf8("lblConfidence"));
        lblConfidence->setGeometry(QRect(10, 0, 81, 21));
        destinationFrame = new QFrame(tab);
        destinationFrame->setObjectName(QString::fromUtf8("destinationFrame"));
        destinationFrame->setGeometry(QRect(490, 270, 111, 71));
        destinationFrame->setStyleSheet(QString::fromUtf8(""));
        destinationFrame->setFrameShape(QFrame::StyledPanel);
        destinationFrame->setFrameShadow(QFrame::Raised);
        lblDestinationGate = new QLabel(destinationFrame);
        lblDestinationGate->setObjectName(QString::fromUtf8("lblDestinationGate"));
        lblDestinationGate->setGeometry(QRect(30, 30, 51, 31));
        lblDestinationGate->setFont(font3);
        lblDestinationGate->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblDestination = new QLabel(destinationFrame);
        lblDestination->setObjectName(QString::fromUtf8("lblDestination"));
        lblDestination->setGeometry(QRect(10, 0, 81, 21));
        btnNetWeightConnect = new QPushButton(tab);
        btnNetWeightConnect->setObjectName(QString::fromUtf8("btnNetWeightConnect"));
        btnNetWeightConnect->setGeometry(QRect(10, 270, 111, 71));
        QPalette palette1;
        QBrush brush1(QColor(0, 0, 0, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        QBrush brush2(QColor(100, 135, 223, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush2);
        QBrush brush3(QColor(194, 212, 255, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush3);
        QBrush brush4(QColor(147, 173, 239, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        QBrush brush5(QColor(50, 67, 111, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush5);
        QBrush brush6(QColor(66, 90, 149, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush1);
        QBrush brush7(QColor(255, 255, 255, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush7);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Highlight, brush7);
        QBrush brush8(QColor(177, 195, 239, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        QBrush brush9(QColor(255, 255, 220, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush9);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        QBrush brush10(QColor(229, 227, 225, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Inactive, QPalette::Highlight, brush10);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush9);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        QBrush brush11(QColor(240, 240, 240, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Disabled, QPalette::Highlight, brush11);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush9);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        btnNetWeightConnect->setPalette(palette1);
        btnNetWeightConnect->setFont(font4);
        btnDisconnect = new QPushButton(tab);
        btnDisconnect->setObjectName(QString::fromUtf8("btnDisconnect"));
        btnDisconnect->setGeometry(QRect(130, 270, 111, 71));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush7);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush7);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush2);
        QBrush brush12(QColor(159, 158, 158, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush2);
        btnDisconnect->setPalette(palette2);
        btnDisconnect->setFont(font4);
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        destinationFrame_2 = new QFrame(tab_2);
        destinationFrame_2->setObjectName(QString::fromUtf8("destinationFrame_2"));
        destinationFrame_2->setGeometry(QRect(10, 270, 111, 71));
        destinationFrame_2->setStyleSheet(QString::fromUtf8(""));
        destinationFrame_2->setFrameShape(QFrame::StyledPanel);
        destinationFrame_2->setFrameShadow(QFrame::Raised);
        lblDestinationGate_2 = new QLabel(destinationFrame_2);
        lblDestinationGate_2->setObjectName(QString::fromUtf8("lblDestinationGate_2"));
        lblDestinationGate_2->setGeometry(QRect(30, 30, 51, 31));
        lblDestinationGate_2->setFont(font3);
        lblDestinationGate_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblDestinationGate_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lblDestination_2 = new QLabel(destinationFrame_2);
        lblDestination_2->setObjectName(QString::fromUtf8("lblDestination_2"));
        lblDestination_2->setGeometry(QRect(10, 0, 81, 21));
        serialFrame_2 = new QFrame(tab_2);
        serialFrame_2->setObjectName(QString::fromUtf8("serialFrame_2"));
        serialFrame_2->setGeometry(QRect(10, 100, 111, 71));
        serialFrame_2->setStyleSheet(QString::fromUtf8(""));
        serialFrame_2->setFrameShape(QFrame::StyledPanel);
        serialFrame_2->setFrameShadow(QFrame::Raised);
        lblSerialNumber_2 = new QLabel(serialFrame_2);
        lblSerialNumber_2->setObjectName(QString::fromUtf8("lblSerialNumber_2"));
        lblSerialNumber_2->setGeometry(QRect(20, 30, 81, 31));
        lblSerialNumber_2->setFont(font3);
        lblSerialNumber_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblSerialNumber_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lblSerial_2 = new QLabel(serialFrame_2);
        lblSerial_2->setObjectName(QString::fromUtf8("lblSerial_2"));
        lblSerial_2->setGeometry(QRect(10, 0, 81, 21));
        filteredWeightFrame_2 = new QFrame(tab_2);
        filteredWeightFrame_2->setObjectName(QString::fromUtf8("filteredWeightFrame_2"));
        filteredWeightFrame_2->setGeometry(QRect(10, 190, 111, 71));
        filteredWeightFrame_2->setStyleSheet(QString::fromUtf8(""));
        filteredWeightFrame_2->setFrameShape(QFrame::StyledPanel);
        filteredWeightFrame_2->setFrameShadow(QFrame::Raised);
        lblProductWeight_2 = new QLabel(filteredWeightFrame_2);
        lblProductWeight_2->setObjectName(QString::fromUtf8("lblProductWeight_2"));
        lblProductWeight_2->setGeometry(QRect(10, 20, 91, 31));
        lblProductWeight_2->setFont(font1);
        lblProductWeight_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblProductWeight_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lblWeightHeader_2 = new QLabel(filteredWeightFrame_2);
        lblWeightHeader_2->setObjectName(QString::fromUtf8("lblWeightHeader_2"));
        lblWeightHeader_2->setGeometry(QRect(6, 0, 91, 21));
        batchFrame_2 = new QFrame(tab_2);
        batchFrame_2->setObjectName(QString::fromUtf8("batchFrame_2"));
        batchFrame_2->setGeometry(QRect(10, 20, 111, 71));
        batchFrame_2->setStyleSheet(QString::fromUtf8(""));
        batchFrame_2->setFrameShape(QFrame::StyledPanel);
        batchFrame_2->setFrameShadow(QFrame::Raised);
        lblBatchID_2 = new QLabel(batchFrame_2);
        lblBatchID_2->setObjectName(QString::fromUtf8("lblBatchID_2"));
        lblBatchID_2->setGeometry(QRect(10, 30, 91, 31));
        lblBatchID_2->setFont(font4);
        lblBatchID_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblBatchID_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lblBatch_2 = new QLabel(batchFrame_2);
        lblBatch_2->setObjectName(QString::fromUtf8("lblBatch_2"));
        lblBatch_2->setGeometry(QRect(10, 0, 81, 21));
        FrameGateBufferStatus = new QFrame(tab_2);
        FrameGateBufferStatus->setObjectName(QString::fromUtf8("FrameGateBufferStatus"));
        FrameGateBufferStatus->setGeometry(QRect(140, 20, 111, 201));
        FrameGateBufferStatus->setStyleSheet(QString::fromUtf8(""));
        FrameGateBufferStatus->setFrameShape(QFrame::StyledPanel);
        FrameGateBufferStatus->setFrameShadow(QFrame::Raised);
        cbxGate1 = new QCheckBox(FrameGateBufferStatus);
        cbxGate1->setObjectName(QString::fromUtf8("cbxGate1"));
        cbxGate1->setGeometry(QRect(10, 20, 81, 22));
        QFont font5;
        font5.setBold(true);
        font5.setWeight(75);
        cbxGate1->setFont(font5);
        cbxGate2 = new QCheckBox(FrameGateBufferStatus);
        cbxGate2->setObjectName(QString::fromUtf8("cbxGate2"));
        cbxGate2->setGeometry(QRect(10, 50, 81, 22));
        cbxGate2->setFont(font5);
        cbxGate3 = new QCheckBox(FrameGateBufferStatus);
        cbxGate3->setObjectName(QString::fromUtf8("cbxGate3"));
        cbxGate3->setGeometry(QRect(10, 80, 81, 21));
        cbxGate3->setFont(font5);
        cbxGate4 = new QCheckBox(FrameGateBufferStatus);
        cbxGate4->setObjectName(QString::fromUtf8("cbxGate4"));
        cbxGate4->setGeometry(QRect(10, 110, 81, 22));
        cbxGate4->setFont(font5);
        cbxGate5 = new QCheckBox(FrameGateBufferStatus);
        cbxGate5->setObjectName(QString::fromUtf8("cbxGate5"));
        cbxGate5->setGeometry(QRect(10, 140, 81, 22));
        cbxGate5->setFont(font5);
        cbxGate6 = new QCheckBox(FrameGateBufferStatus);
        cbxGate6->setObjectName(QString::fromUtf8("cbxGate6"));
        cbxGate6->setGeometry(QRect(10, 170, 81, 22));
        cbxGate6->setFont(font5);
        lblGateStatus = new QLabel(FrameGateBufferStatus);
        lblGateStatus->setObjectName(QString::fromUtf8("lblGateStatus"));
        lblGateStatus->setGeometry(QRect(10, 0, 61, 21));
        FrameBufferWeight = new QFrame(tab_2);
        FrameBufferWeight->setObjectName(QString::fromUtf8("FrameBufferWeight"));
        FrameBufferWeight->setGeometry(QRect(250, 20, 91, 201));
        FrameBufferWeight->setStyleSheet(QString::fromUtf8(""));
        FrameBufferWeight->setFrameShape(QFrame::StyledPanel);
        FrameBufferWeight->setFrameShadow(QFrame::Raised);
        lblBWgt1 = new QLabel(FrameBufferWeight);
        lblBWgt1->setObjectName(QString::fromUtf8("lblBWgt1"));
        lblBWgt1->setGeometry(QRect(10, 20, 61, 21));
        lblBWgt1->setFont(font4);
        lblBWgt1->setLayoutDirection(Qt::LeftToRight);
        lblBWgt1->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblBWgt1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lblBWgt2 = new QLabel(FrameBufferWeight);
        lblBWgt2->setObjectName(QString::fromUtf8("lblBWgt2"));
        lblBWgt2->setGeometry(QRect(10, 50, 61, 21));
        lblBWgt2->setFont(font4);
        lblBWgt2->setLayoutDirection(Qt::LeftToRight);
        lblBWgt2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblBWgt2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lblBWgt3 = new QLabel(FrameBufferWeight);
        lblBWgt3->setObjectName(QString::fromUtf8("lblBWgt3"));
        lblBWgt3->setGeometry(QRect(10, 80, 61, 21));
        lblBWgt3->setFont(font4);
        lblBWgt3->setLayoutDirection(Qt::LeftToRight);
        lblBWgt3->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblBWgt3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lblBWgt4 = new QLabel(FrameBufferWeight);
        lblBWgt4->setObjectName(QString::fromUtf8("lblBWgt4"));
        lblBWgt4->setGeometry(QRect(10, 110, 61, 21));
        lblBWgt4->setFont(font4);
        lblBWgt4->setLayoutDirection(Qt::LeftToRight);
        lblBWgt4->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblBWgt4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lblBWgt5 = new QLabel(FrameBufferWeight);
        lblBWgt5->setObjectName(QString::fromUtf8("lblBWgt5"));
        lblBWgt5->setGeometry(QRect(10, 140, 61, 21));
        lblBWgt5->setFont(font4);
        lblBWgt5->setLayoutDirection(Qt::LeftToRight);
        lblBWgt5->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblBWgt5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lblBWgt6 = new QLabel(FrameBufferWeight);
        lblBWgt6->setObjectName(QString::fromUtf8("lblBWgt6"));
        lblBWgt6->setGeometry(QRect(10, 170, 61, 21));
        lblBWgt6->setFont(font4);
        lblBWgt6->setLayoutDirection(Qt::LeftToRight);
        lblBWgt6->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblBWgt6->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lblBWgt = new QLabel(FrameBufferWeight);
        lblBWgt->setObjectName(QString::fromUtf8("lblBWgt"));
        lblBWgt->setGeometry(QRect(10, 0, 81, 21));
        FrameBufferCount = new QFrame(tab_2);
        FrameBufferCount->setObjectName(QString::fromUtf8("FrameBufferCount"));
        FrameBufferCount->setGeometry(QRect(340, 20, 81, 201));
        FrameBufferCount->setStyleSheet(QString::fromUtf8(""));
        FrameBufferCount->setFrameShape(QFrame::StyledPanel);
        FrameBufferCount->setFrameShadow(QFrame::Raised);
        lblBCnt1 = new QLabel(FrameBufferCount);
        lblBCnt1->setObjectName(QString::fromUtf8("lblBCnt1"));
        lblBCnt1->setGeometry(QRect(10, 20, 51, 21));
        lblBCnt1->setFont(font4);
        lblBCnt1->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblBCnt1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lblBCnt2 = new QLabel(FrameBufferCount);
        lblBCnt2->setObjectName(QString::fromUtf8("lblBCnt2"));
        lblBCnt2->setGeometry(QRect(10, 50, 51, 21));
        lblBCnt2->setFont(font4);
        lblBCnt2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblBCnt2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lblBCnt3 = new QLabel(FrameBufferCount);
        lblBCnt3->setObjectName(QString::fromUtf8("lblBCnt3"));
        lblBCnt3->setGeometry(QRect(10, 80, 51, 21));
        lblBCnt3->setFont(font4);
        lblBCnt3->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblBCnt3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lblBCnt4 = new QLabel(FrameBufferCount);
        lblBCnt4->setObjectName(QString::fromUtf8("lblBCnt4"));
        lblBCnt4->setGeometry(QRect(10, 110, 51, 21));
        lblBCnt4->setFont(font4);
        lblBCnt4->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblBCnt4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lblBCnt5 = new QLabel(FrameBufferCount);
        lblBCnt5->setObjectName(QString::fromUtf8("lblBCnt5"));
        lblBCnt5->setGeometry(QRect(10, 140, 51, 21));
        lblBCnt5->setFont(font4);
        lblBCnt5->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblBCnt5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lblBCnt6 = new QLabel(FrameBufferCount);
        lblBCnt6->setObjectName(QString::fromUtf8("lblBCnt6"));
        lblBCnt6->setGeometry(QRect(10, 170, 51, 21));
        lblBCnt6->setFont(font4);
        lblBCnt6->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblBCnt6->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lblBCnt = new QLabel(FrameBufferCount);
        lblBCnt->setObjectName(QString::fromUtf8("lblBCnt"));
        lblBCnt->setGeometry(QRect(10, 0, 71, 21));
        btnCloseBatch = new QPushButton(tab_2);
        btnCloseBatch->setObjectName(QString::fromUtf8("btnCloseBatch"));
        btnCloseBatch->setGeometry(QRect(130, 270, 111, 71));
        btnCloseBatch->setFont(font5);
        btnCloseBatch->setAcceptDrops(false);
        btnCloseBatch->setCheckable(false);
        tabWidget->addTab(tab_2, QString());
        tabGraph = new QWidget();
        tabGraph->setObjectName(QString::fromUtf8("tabGraph"));
        verticalLayout = new QVBoxLayout(tabGraph);
        verticalLayout->setSpacing(6);
        verticalLayout->setContentsMargins(11, 11, 11, 11);
        verticalLayout->setObjectName(QString::fromUtf8("verticalLayout"));
        widget = new QWidget(tabGraph);
        widget->setObjectName(QString::fromUtf8("widget"));
        frame_4 = new QFrame(widget);
        frame_4->setObjectName(QString::fromUtf8("frame_4"));
        frame_4->setGeometry(QRect(40, 10, 551, 161));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Raised);
        customPlot = new QCustomPlot(frame_4);
        customPlot->setObjectName(QString::fromUtf8("customPlot"));
        customPlot->setEnabled(true);
        customPlot->setGeometry(QRect(10, 10, 531, 141));
        customPlot->setAutoFillBackground(false);
        lblFilteredWeight = new QLabel(widget);
        lblFilteredWeight->setObjectName(QString::fromUtf8("lblFilteredWeight"));
        lblFilteredWeight->setGeometry(QRect(300, 220, 141, 31));
        lblFilteredWeight->setFont(font1);
        lblFilteredWeight->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        btnForward = new QPushButton(widget);
        btnForward->setObjectName(QString::fromUtf8("btnForward"));
        btnForward->setGeometry(QRect(290, 260, 97, 31));
        btnReverse = new QPushButton(widget);
        btnReverse->setObjectName(QString::fromUtf8("btnReverse"));
        btnReverse->setGeometry(QRect(190, 260, 97, 31));
        lblElementId = new QLabel(widget);
        lblElementId->setObjectName(QString::fromUtf8("lblElementId"));
        lblElementId->setGeometry(QRect(110, 220, 161, 31));
        lblElementId->setFont(font1);
        lblElementId->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        ymax = new QPushButton(widget);
        ymax->setObjectName(QString::fromUtf8("ymax"));
        ymax->setGeometry(QRect(0, 10, 41, 31));
        QFont font6;
        font6.setPointSize(10);
        font6.setBold(true);
        font6.setWeight(75);
        ymax->setFont(font6);
        ymin = new QPushButton(widget);
        ymin->setObjectName(QString::fromUtf8("ymin"));
        ymin->setGeometry(QRect(0, 50, 41, 31));
        ymin->setFont(font6);
        xmin = new QPushButton(widget);
        xmin->setObjectName(QString::fromUtf8("xmin"));
        xmin->setGeometry(QRect(0, 130, 41, 31));
        xmin->setFont(font6);
        xmax = new QPushButton(widget);
        xmax->setObjectName(QString::fromUtf8("xmax"));
        xmax->setGeometry(QRect(0, 90, 41, 31));
        xmax->setFont(font6);

        verticalLayout->addWidget(widget);

        tabWidget->addTab(tabGraph, QString());
        tabSettings = new QWidget();
        tabSettings->setObjectName(QString::fromUtf8("tabSettings"));
        cbSettingsMenu = new QComboBox(tabSettings);
        cbSettingsMenu->setObjectName(QString::fromUtf8("cbSettingsMenu"));
        cbSettingsMenu->setGeometry(QRect(10, 10, 451, 41));
        cbSettingsMenu->setFont(font3);
        btnRefreshSettingsList = new QPushButton(tabSettings);
        btnRefreshSettingsList->setObjectName(QString::fromUtf8("btnRefreshSettingsList"));
        btnRefreshSettingsList->setGeometry(QRect(480, 10, 131, 41));
        settingsTable = new QTableWidget(tabSettings);
        if (settingsTable->columnCount() < 2)
            settingsTable->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        settingsTable->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        settingsTable->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        if (settingsTable->rowCount() < 40)
            settingsTable->setRowCount(40);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(0, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(1, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(2, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(3, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(4, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(5, __qtablewidgetitem7);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(6, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(7, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(8, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(9, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(10, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(11, __qtablewidgetitem13);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(12, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(13, __qtablewidgetitem15);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(14, __qtablewidgetitem16);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(15, __qtablewidgetitem17);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(16, __qtablewidgetitem18);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(17, __qtablewidgetitem19);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(18, __qtablewidgetitem20);
        QTableWidgetItem *__qtablewidgetitem21 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(19, __qtablewidgetitem21);
        QTableWidgetItem *__qtablewidgetitem22 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(20, __qtablewidgetitem22);
        QTableWidgetItem *__qtablewidgetitem23 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(21, __qtablewidgetitem23);
        QTableWidgetItem *__qtablewidgetitem24 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(22, __qtablewidgetitem24);
        QTableWidgetItem *__qtablewidgetitem25 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(23, __qtablewidgetitem25);
        QTableWidgetItem *__qtablewidgetitem26 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(24, __qtablewidgetitem26);
        QTableWidgetItem *__qtablewidgetitem27 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(25, __qtablewidgetitem27);
        QTableWidgetItem *__qtablewidgetitem28 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(26, __qtablewidgetitem28);
        QTableWidgetItem *__qtablewidgetitem29 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(27, __qtablewidgetitem29);
        QTableWidgetItem *__qtablewidgetitem30 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(28, __qtablewidgetitem30);
        QTableWidgetItem *__qtablewidgetitem31 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(29, __qtablewidgetitem31);
        QTableWidgetItem *__qtablewidgetitem32 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(30, __qtablewidgetitem32);
        QTableWidgetItem *__qtablewidgetitem33 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(31, __qtablewidgetitem33);
        QTableWidgetItem *__qtablewidgetitem34 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(32, __qtablewidgetitem34);
        QTableWidgetItem *__qtablewidgetitem35 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(33, __qtablewidgetitem35);
        QTableWidgetItem *__qtablewidgetitem36 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(34, __qtablewidgetitem36);
        QTableWidgetItem *__qtablewidgetitem37 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(35, __qtablewidgetitem37);
        QTableWidgetItem *__qtablewidgetitem38 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(36, __qtablewidgetitem38);
        QTableWidgetItem *__qtablewidgetitem39 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(37, __qtablewidgetitem39);
        QTableWidgetItem *__qtablewidgetitem40 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(38, __qtablewidgetitem40);
        QTableWidgetItem *__qtablewidgetitem41 = new QTableWidgetItem();
        settingsTable->setVerticalHeaderItem(39, __qtablewidgetitem41);
        settingsTable->setObjectName(QString::fromUtf8("settingsTable"));
        settingsTable->setGeometry(QRect(10, 60, 601, 281));
        settingsTable->setMinimumSize(QSize(451, 0));
        settingsTable->setStyleSheet(QString::fromUtf8("QScrollBar:vertical {min-width: 50px; margin-right: 20px;}"));
        settingsTable->setAutoScrollMargin(16);
        tabWidget->addTab(tabSettings, QString());
        tabRecipe = new QWidget();
        tabRecipe->setObjectName(QString::fromUtf8("tabRecipe"));
        btnRefreshRecipeList = new QPushButton(tabRecipe);
        btnRefreshRecipeList->setObjectName(QString::fromUtf8("btnRefreshRecipeList"));
        btnRefreshRecipeList->setGeometry(QRect(480, 10, 131, 41));
        cbRecipeMenu = new QComboBox(tabRecipe);
        cbRecipeMenu->setObjectName(QString::fromUtf8("cbRecipeMenu"));
        cbRecipeMenu->setGeometry(QRect(10, 10, 451, 41));
        cbRecipeMenu->setFont(font3);
        cbRecipeMenu->setSizeAdjustPolicy(QComboBox::AdjustToMinimumContentsLengthWithIcon);
        cbRecipeMenu->setMinimumContentsLength(10);
        cbRecipeMenu->setIconSize(QSize(16, 16));
        recipeTable = new QTableWidget(tabRecipe);
        if (recipeTable->columnCount() < 4)
            recipeTable->setColumnCount(4);
        QTableWidgetItem *__qtablewidgetitem42 = new QTableWidgetItem();
        recipeTable->setHorizontalHeaderItem(0, __qtablewidgetitem42);
        QTableWidgetItem *__qtablewidgetitem43 = new QTableWidgetItem();
        recipeTable->setHorizontalHeaderItem(1, __qtablewidgetitem43);
        QTableWidgetItem *__qtablewidgetitem44 = new QTableWidgetItem();
        recipeTable->setHorizontalHeaderItem(2, __qtablewidgetitem44);
        QTableWidgetItem *__qtablewidgetitem45 = new QTableWidgetItem();
        recipeTable->setHorizontalHeaderItem(3, __qtablewidgetitem45);
        if (recipeTable->rowCount() < 66)
            recipeTable->setRowCount(66);
        QTableWidgetItem *__qtablewidgetitem46 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(0, __qtablewidgetitem46);
        QTableWidgetItem *__qtablewidgetitem47 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(1, __qtablewidgetitem47);
        QTableWidgetItem *__qtablewidgetitem48 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(2, __qtablewidgetitem48);
        QTableWidgetItem *__qtablewidgetitem49 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(3, __qtablewidgetitem49);
        QTableWidgetItem *__qtablewidgetitem50 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(4, __qtablewidgetitem50);
        QTableWidgetItem *__qtablewidgetitem51 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(5, __qtablewidgetitem51);
        QTableWidgetItem *__qtablewidgetitem52 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(6, __qtablewidgetitem52);
        QTableWidgetItem *__qtablewidgetitem53 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(7, __qtablewidgetitem53);
        QTableWidgetItem *__qtablewidgetitem54 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(8, __qtablewidgetitem54);
        QTableWidgetItem *__qtablewidgetitem55 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(9, __qtablewidgetitem55);
        QTableWidgetItem *__qtablewidgetitem56 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(10, __qtablewidgetitem56);
        QTableWidgetItem *__qtablewidgetitem57 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(11, __qtablewidgetitem57);
        QTableWidgetItem *__qtablewidgetitem58 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(12, __qtablewidgetitem58);
        QTableWidgetItem *__qtablewidgetitem59 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(13, __qtablewidgetitem59);
        QTableWidgetItem *__qtablewidgetitem60 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(14, __qtablewidgetitem60);
        QTableWidgetItem *__qtablewidgetitem61 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(15, __qtablewidgetitem61);
        QTableWidgetItem *__qtablewidgetitem62 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(16, __qtablewidgetitem62);
        QTableWidgetItem *__qtablewidgetitem63 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(17, __qtablewidgetitem63);
        QTableWidgetItem *__qtablewidgetitem64 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(18, __qtablewidgetitem64);
        QTableWidgetItem *__qtablewidgetitem65 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(19, __qtablewidgetitem65);
        QTableWidgetItem *__qtablewidgetitem66 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(20, __qtablewidgetitem66);
        QTableWidgetItem *__qtablewidgetitem67 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(21, __qtablewidgetitem67);
        QTableWidgetItem *__qtablewidgetitem68 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(22, __qtablewidgetitem68);
        QTableWidgetItem *__qtablewidgetitem69 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(23, __qtablewidgetitem69);
        QTableWidgetItem *__qtablewidgetitem70 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(24, __qtablewidgetitem70);
        QTableWidgetItem *__qtablewidgetitem71 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(25, __qtablewidgetitem71);
        QTableWidgetItem *__qtablewidgetitem72 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(26, __qtablewidgetitem72);
        QTableWidgetItem *__qtablewidgetitem73 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(27, __qtablewidgetitem73);
        QTableWidgetItem *__qtablewidgetitem74 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(28, __qtablewidgetitem74);
        QTableWidgetItem *__qtablewidgetitem75 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(29, __qtablewidgetitem75);
        QTableWidgetItem *__qtablewidgetitem76 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(30, __qtablewidgetitem76);
        QTableWidgetItem *__qtablewidgetitem77 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(31, __qtablewidgetitem77);
        QTableWidgetItem *__qtablewidgetitem78 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(32, __qtablewidgetitem78);
        QTableWidgetItem *__qtablewidgetitem79 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(33, __qtablewidgetitem79);
        QTableWidgetItem *__qtablewidgetitem80 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(34, __qtablewidgetitem80);
        QTableWidgetItem *__qtablewidgetitem81 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(35, __qtablewidgetitem81);
        QTableWidgetItem *__qtablewidgetitem82 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(36, __qtablewidgetitem82);
        QTableWidgetItem *__qtablewidgetitem83 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(37, __qtablewidgetitem83);
        QTableWidgetItem *__qtablewidgetitem84 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(38, __qtablewidgetitem84);
        QTableWidgetItem *__qtablewidgetitem85 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(39, __qtablewidgetitem85);
        QTableWidgetItem *__qtablewidgetitem86 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(40, __qtablewidgetitem86);
        QTableWidgetItem *__qtablewidgetitem87 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(41, __qtablewidgetitem87);
        QTableWidgetItem *__qtablewidgetitem88 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(42, __qtablewidgetitem88);
        QTableWidgetItem *__qtablewidgetitem89 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(43, __qtablewidgetitem89);
        QTableWidgetItem *__qtablewidgetitem90 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(44, __qtablewidgetitem90);
        QTableWidgetItem *__qtablewidgetitem91 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(45, __qtablewidgetitem91);
        QTableWidgetItem *__qtablewidgetitem92 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(46, __qtablewidgetitem92);
        QTableWidgetItem *__qtablewidgetitem93 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(47, __qtablewidgetitem93);
        QTableWidgetItem *__qtablewidgetitem94 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(48, __qtablewidgetitem94);
        QTableWidgetItem *__qtablewidgetitem95 = new QTableWidgetItem();
        recipeTable->setVerticalHeaderItem(49, __qtablewidgetitem95);
        recipeTable->setObjectName(QString::fromUtf8("recipeTable"));
        recipeTable->setGeometry(QRect(10, 60, 601, 281));
        recipeTable->setMinimumSize(QSize(451, 0));
        recipeTable->setStyleSheet(QString::fromUtf8("QScrollBar:vertical {min-width: 50px; margin-right: 20px;}"));
        recipeTable->setRowCount(66);
        tabWidget->addTab(tabRecipe, QString());
        tabDio = new QWidget();
        tabDio->setObjectName(QString::fromUtf8("tabDio"));
        layoutWidget_1 = new QWidget(tabDio);
        layoutWidget_1->setObjectName(QString::fromUtf8("layoutWidget_1"));
        layoutWidget_1->setGeometry(QRect(10, 70, 321, 33));
        horizontalLayout_3 = new QHBoxLayout(layoutWidget_1);
        horizontalLayout_3->setSpacing(6);
        horizontalLayout_3->setContentsMargins(11, 11, 11, 11);
        horizontalLayout_3->setObjectName(QString::fromUtf8("horizontalLayout_3"));
        horizontalLayout_3->setContentsMargins(0, 0, 0, 0);
        chkDIN_03 = new QCheckBox(layoutWidget_1);
        chkDIN_03->setObjectName(QString::fromUtf8("chkDIN_03"));

        horizontalLayout_3->addWidget(chkDIN_03);

        horizontalSpacer_5 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout_3->addItem(horizontalSpacer_5);

        label_6 = new QLabel(layoutWidget_1);
        label_6->setObjectName(QString::fromUtf8("label_6"));

        horizontalLayout_3->addWidget(label_6);

        lblDIN_03 = new QLabel(layoutWidget_1);
        lblDIN_03->setObjectName(QString::fromUtf8("lblDIN_03"));

        horizontalLayout_3->addWidget(lblDIN_03);

        horizontalSpacer_6 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout_3->addItem(horizontalSpacer_6);

        label_7 = new QLabel(layoutWidget_1);
        label_7->setObjectName(QString::fromUtf8("label_7"));

        horizontalLayout_3->addWidget(label_7);

        lblDOUT_03 = new QLabel(layoutWidget_1);
        lblDOUT_03->setObjectName(QString::fromUtf8("lblDOUT_03"));

        horizontalLayout_3->addWidget(lblDOUT_03);

        layoutWidget_2 = new QWidget(tabDio);
        layoutWidget_2->setObjectName(QString::fromUtf8("layoutWidget_2"));
        layoutWidget_2->setGeometry(QRect(10, 100, 321, 33));
        horizontalLayout_4 = new QHBoxLayout(layoutWidget_2);
        horizontalLayout_4->setSpacing(6);
        horizontalLayout_4->setContentsMargins(11, 11, 11, 11);
        horizontalLayout_4->setObjectName(QString::fromUtf8("horizontalLayout_4"));
        horizontalLayout_4->setContentsMargins(0, 0, 0, 0);
        chkDIN_04 = new QCheckBox(layoutWidget_2);
        chkDIN_04->setObjectName(QString::fromUtf8("chkDIN_04"));

        horizontalLayout_4->addWidget(chkDIN_04);

        horizontalSpacer_7 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout_4->addItem(horizontalSpacer_7);

        label_8 = new QLabel(layoutWidget_2);
        label_8->setObjectName(QString::fromUtf8("label_8"));

        horizontalLayout_4->addWidget(label_8);

        lblDIN_04 = new QLabel(layoutWidget_2);
        lblDIN_04->setObjectName(QString::fromUtf8("lblDIN_04"));

        horizontalLayout_4->addWidget(lblDIN_04);

        horizontalSpacer_8 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout_4->addItem(horizontalSpacer_8);

        label_9 = new QLabel(layoutWidget_2);
        label_9->setObjectName(QString::fromUtf8("label_9"));

        horizontalLayout_4->addWidget(label_9);

        lblDOUT_04 = new QLabel(layoutWidget_2);
        lblDOUT_04->setObjectName(QString::fromUtf8("lblDOUT_04"));

        horizontalLayout_4->addWidget(lblDOUT_04);

        layoutWidget_3 = new QWidget(tabDio);
        layoutWidget_3->setObjectName(QString::fromUtf8("layoutWidget_3"));
        layoutWidget_3->setGeometry(QRect(10, 10, 321, 33));
        horizontalLayout = new QHBoxLayout(layoutWidget_3);
        horizontalLayout->setSpacing(6);
        horizontalLayout->setContentsMargins(11, 11, 11, 11);
        horizontalLayout->setObjectName(QString::fromUtf8("horizontalLayout"));
        horizontalLayout->setContentsMargins(0, 0, 0, 0);
        chkDIN_01 = new QCheckBox(layoutWidget_3);
        chkDIN_01->setObjectName(QString::fromUtf8("chkDIN_01"));
        chkDIN_01->setChecked(false);

        horizontalLayout->addWidget(chkDIN_01);

        horizontalSpacer = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout->addItem(horizontalSpacer);

        label_2 = new QLabel(layoutWidget_3);
        label_2->setObjectName(QString::fromUtf8("label_2"));

        horizontalLayout->addWidget(label_2);

        lblDIN_01 = new QLabel(layoutWidget_3);
        lblDIN_01->setObjectName(QString::fromUtf8("lblDIN_01"));
        lblDIN_01->setEnabled(true);
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::Button, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush2);
        lblDIN_01->setPalette(palette3);
        lblDIN_01->setAutoFillBackground(false);

        horizontalLayout->addWidget(lblDIN_01);

        horizontalSpacer_2 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout->addItem(horizontalSpacer_2);

        label_4 = new QLabel(layoutWidget_3);
        label_4->setObjectName(QString::fromUtf8("label_4"));

        horizontalLayout->addWidget(label_4);

        lblDOUT_01 = new QLabel(layoutWidget_3);
        lblDOUT_01->setObjectName(QString::fromUtf8("lblDOUT_01"));

        horizontalLayout->addWidget(lblDOUT_01);

        layoutWidget_4 = new QWidget(tabDio);
        layoutWidget_4->setObjectName(QString::fromUtf8("layoutWidget_4"));
        layoutWidget_4->setGeometry(QRect(10, 40, 321, 33));
        horizontalLayout_2 = new QHBoxLayout(layoutWidget_4);
        horizontalLayout_2->setSpacing(6);
        horizontalLayout_2->setContentsMargins(11, 11, 11, 11);
        horizontalLayout_2->setObjectName(QString::fromUtf8("horizontalLayout_2"));
        horizontalLayout_2->setContentsMargins(0, 0, 0, 0);
        chkDIN_02 = new QCheckBox(layoutWidget_4);
        chkDIN_02->setObjectName(QString::fromUtf8("chkDIN_02"));

        horizontalLayout_2->addWidget(chkDIN_02);

        horizontalSpacer_3 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout_2->addItem(horizontalSpacer_3);

        label_3 = new QLabel(layoutWidget_4);
        label_3->setObjectName(QString::fromUtf8("label_3"));

        horizontalLayout_2->addWidget(label_3);

        lblDIN_02 = new QLabel(layoutWidget_4);
        lblDIN_02->setObjectName(QString::fromUtf8("lblDIN_02"));

        horizontalLayout_2->addWidget(lblDIN_02);

        horizontalSpacer_4 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout_2->addItem(horizontalSpacer_4);

        label_5 = new QLabel(layoutWidget_4);
        label_5->setObjectName(QString::fromUtf8("label_5"));

        horizontalLayout_2->addWidget(label_5);

        lblDOUT_02 = new QLabel(layoutWidget_4);
        lblDOUT_02->setObjectName(QString::fromUtf8("lblDOUT_02"));

        horizontalLayout_2->addWidget(lblDOUT_02);

        transmitFrame = new QFrame(tabDio);
        transmitFrame->setObjectName(QString::fromUtf8("transmitFrame"));
        transmitFrame->setGeometry(QRect(10, 160, 321, 201));
        transmitFrame->setStyleSheet(QString::fromUtf8(""));
        transmitFrame->setFrameShape(QFrame::StyledPanel);
        transmitFrame->setFrameShadow(QFrame::Raised);
        btnCalibrateZERO = new QPushButton(transmitFrame);
        btnCalibrateZERO->setObjectName(QString::fromUtf8("btnCalibrateZERO"));
        btnCalibrateZERO->setGeometry(QRect(10, 80, 131, 51));
        btnCalibrateZERO->setAutoFillBackground(false);
        btnCalibrateZERO->setStyleSheet(QString::fromUtf8(""));
        btnCalibrateWEIGHT = new QPushButton(transmitFrame);
        btnCalibrateWEIGHT->setObjectName(QString::fromUtf8("btnCalibrateWEIGHT"));
        btnCalibrateWEIGHT->setGeometry(QRect(10, 140, 131, 51));
        label = new QLabel(transmitFrame);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 0, 131, 21));
        chkWriteToLoadcell = new QCheckBox(transmitFrame);
        chkWriteToLoadcell->setObjectName(QString::fromUtf8("chkWriteToLoadcell"));
        chkWriteToLoadcell->setGeometry(QRect(20, 30, 91, 26));
        chkWriteToLoadcell->setIconSize(QSize(16, 16));
        chkDebugWriteToFile = new QCheckBox(transmitFrame);
        chkDebugWriteToFile->setObjectName(QString::fromUtf8("chkDebugWriteToFile"));
        chkDebugWriteToFile->setGeometry(QRect(190, 30, 91, 26));
        tabWidget->addTab(tabDio, QString());
        frameState = new QFrame(frame_2);
        frameState->setObjectName(QString::fromUtf8("frameState"));
        frameState->setGeometry(QRect(20, 460, 621, 51));
        frameState->setStyleSheet(QString::fromUtf8("background-color: rgb(21, 208, 21);"));
        frameState->setFrameShape(QFrame::StyledPanel);
        frameState->setFrameShadow(QFrame::Raised);
        lblSystemState = new QLabel(frameState);
        lblSystemState->setObjectName(QString::fromUtf8("lblSystemState"));
        lblSystemState->setGeometry(QRect(20, 10, 491, 31));
        lblSystemState->setFont(font3);
        lblSystemState->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        lblCountDown = new QLabel(frameState);
        lblCountDown->setObjectName(QString::fromUtf8("lblCountDown"));
        lblCountDown->setGeometry(QRect(520, 10, 91, 31));
        lblCountDown->setFont(font3);
        lblCountDown->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        MainWindow->setCentralWidget(centralWidget);
        QWidget::setTabOrder(chkDIN_03, chkDIN_04);
        QWidget::setTabOrder(chkDIN_04, chkDIN_01);
        QWidget::setTabOrder(chkDIN_01, chkDIN_02);
        QWidget::setTabOrder(chkDIN_02, btnForward);
        QWidget::setTabOrder(btnForward, btnReverse);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0, QApplication::UnicodeUTF8));
        lblProductWeight->setText(QApplication::translate("MainWindow", "weight", 0, QApplication::UnicodeUTF8));
        lblWeightHeader->setText(QApplication::translate("MainWindow", "weight", 0, QApplication::UnicodeUTF8));
        lblDescription->setText(QApplication::translate("MainWindow", "description", 0, QApplication::UnicodeUTF8));
        lblDescription_2->setText(QApplication::translate("MainWindow", "description", 0, QApplication::UnicodeUTF8));
        lblRawWeight->setText(QApplication::translate("MainWindow", "rwWgt", 0, QApplication::UnicodeUTF8));
        lblRawWeight_2->setText(QApplication::translate("MainWindow", "rawWeight", 0, QApplication::UnicodeUTF8));
        lblBatchID->setText(QApplication::translate("MainWindow", "batchID", 0, QApplication::UnicodeUTF8));
        lblBatch->setText(QApplication::translate("MainWindow", "batch", 0, QApplication::UnicodeUTF8));
        lblSerialNumber->setText(QApplication::translate("MainWindow", "serial", 0, QApplication::UnicodeUTF8));
        lblSerial->setText(QApplication::translate("MainWindow", "serial", 0, QApplication::UnicodeUTF8));
        lblProductID->setText(QApplication::translate("MainWindow", "prodID", 0, QApplication::UnicodeUTF8));
        lblproduct->setText(QApplication::translate("MainWindow", "productID", 0, QApplication::UnicodeUTF8));
        lblRecipeID->setText(QApplication::translate("MainWindow", "recipeID", 0, QApplication::UnicodeUTF8));
        lblRecipe->setText(QApplication::translate("MainWindow", "recipe", 0, QApplication::UnicodeUTF8));
        lblLength->setText(QApplication::translate("MainWindow", "length", 0, QApplication::UnicodeUTF8));
        lblLength_2->setText(QApplication::translate("MainWindow", "length", 0, QApplication::UnicodeUTF8));
        lblWeightConfidence->setText(QApplication::translate("MainWindow", "conf", 0, QApplication::UnicodeUTF8));
        lblConfidence->setText(QApplication::translate("MainWindow", "confidence", 0, QApplication::UnicodeUTF8));
        lblDestinationGate->setText(QApplication::translate("MainWindow", "gate", 0, QApplication::UnicodeUTF8));
        lblDestination->setText(QApplication::translate("MainWindow", "destination", 0, QApplication::UnicodeUTF8));
        btnNetWeightConnect->setText(QApplication::translate("MainWindow", "Connect", 0, QApplication::UnicodeUTF8));
        btnDisconnect->setText(QApplication::translate("MainWindow", "Disconnect", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("MainWindow", "FlowScale", 0, QApplication::UnicodeUTF8));
        lblDestinationGate_2->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        lblDestination_2->setText(QApplication::translate("MainWindow", "destination", 0, QApplication::UnicodeUTF8));
        lblSerialNumber_2->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        lblSerial_2->setText(QApplication::translate("MainWindow", "serial", 0, QApplication::UnicodeUTF8));
        lblProductWeight_2->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        lblWeightHeader_2->setText(QApplication::translate("MainWindow", "weight", 0, QApplication::UnicodeUTF8));
        lblBatchID_2->setText(QApplication::translate("MainWindow", "batchID", 0, QApplication::UnicodeUTF8));
        lblBatch_2->setText(QApplication::translate("MainWindow", "batch", 0, QApplication::UnicodeUTF8));
        cbxGate1->setText(QApplication::translate("MainWindow", "Gate 1", 0, QApplication::UnicodeUTF8));
        cbxGate2->setText(QApplication::translate("MainWindow", "Gate 2", 0, QApplication::UnicodeUTF8));
        cbxGate3->setText(QApplication::translate("MainWindow", "Gate 3", 0, QApplication::UnicodeUTF8));
        cbxGate4->setText(QApplication::translate("MainWindow", "Gate 4", 0, QApplication::UnicodeUTF8));
        cbxGate5->setText(QApplication::translate("MainWindow", "Gate 5", 0, QApplication::UnicodeUTF8));
        cbxGate6->setText(QApplication::translate("MainWindow", "Gate 6", 0, QApplication::UnicodeUTF8));
        lblGateStatus->setText(QApplication::translate("MainWindow", "status", 0, QApplication::UnicodeUTF8));
        lblBWgt1->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        lblBWgt2->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        lblBWgt3->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        lblBWgt4->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        lblBWgt5->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        lblBWgt6->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        lblBWgt->setText(QApplication::translate("MainWindow", "weight[kg]", 0, QApplication::UnicodeUTF8));
        lblBCnt1->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        lblBCnt2->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        lblBCnt3->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        lblBCnt4->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        lblBCnt5->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        lblBCnt6->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        lblBCnt->setText(QApplication::translate("MainWindow", "count[pcs]", 0, QApplication::UnicodeUTF8));
        btnCloseBatch->setText(QApplication::translate("MainWindow", "closeBatch", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("MainWindow", "Grader", 0, QApplication::UnicodeUTF8));
        lblFilteredWeight->setText(QApplication::translate("MainWindow", "Number", 0, QApplication::UnicodeUTF8));
        btnForward->setText(QApplication::translate("MainWindow", "Forward", 0, QApplication::UnicodeUTF8));
        btnReverse->setText(QApplication::translate("MainWindow", "Reverse", 0, QApplication::UnicodeUTF8));
        lblElementId->setText(QApplication::translate("MainWindow", "ElementId", 0, QApplication::UnicodeUTF8));
        ymax->setText(QApplication::translate("MainWindow", "Ymax", 0, QApplication::UnicodeUTF8));
        ymin->setText(QApplication::translate("MainWindow", "Ymin", 0, QApplication::UnicodeUTF8));
        xmin->setText(QApplication::translate("MainWindow", "Xmin", 0, QApplication::UnicodeUTF8));
        xmax->setText(QApplication::translate("MainWindow", "Xmax", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tabGraph), QApplication::translate("MainWindow", "Graph", 0, QApplication::UnicodeUTF8));
        btnRefreshSettingsList->setText(QApplication::translate("MainWindow", "Reload Settings", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem = settingsTable->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QApplication::translate("MainWindow", "01", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem1 = settingsTable->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QApplication::translate("MainWindow", "02", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem2 = settingsTable->verticalHeaderItem(0);
        ___qtablewidgetitem2->setText(QApplication::translate("MainWindow", "01", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem3 = settingsTable->verticalHeaderItem(1);
        ___qtablewidgetitem3->setText(QApplication::translate("MainWindow", "02", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem4 = settingsTable->verticalHeaderItem(2);
        ___qtablewidgetitem4->setText(QApplication::translate("MainWindow", "03", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem5 = settingsTable->verticalHeaderItem(3);
        ___qtablewidgetitem5->setText(QApplication::translate("MainWindow", "04", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem6 = settingsTable->verticalHeaderItem(4);
        ___qtablewidgetitem6->setText(QApplication::translate("MainWindow", "05", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem7 = settingsTable->verticalHeaderItem(5);
        ___qtablewidgetitem7->setText(QApplication::translate("MainWindow", "06", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem8 = settingsTable->verticalHeaderItem(6);
        ___qtablewidgetitem8->setText(QApplication::translate("MainWindow", "07", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem9 = settingsTable->verticalHeaderItem(7);
        ___qtablewidgetitem9->setText(QApplication::translate("MainWindow", "08", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem10 = settingsTable->verticalHeaderItem(8);
        ___qtablewidgetitem10->setText(QApplication::translate("MainWindow", "09", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem11 = settingsTable->verticalHeaderItem(9);
        ___qtablewidgetitem11->setText(QApplication::translate("MainWindow", "10", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem12 = settingsTable->verticalHeaderItem(10);
        ___qtablewidgetitem12->setText(QApplication::translate("MainWindow", "11", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem13 = settingsTable->verticalHeaderItem(11);
        ___qtablewidgetitem13->setText(QApplication::translate("MainWindow", "12", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem14 = settingsTable->verticalHeaderItem(12);
        ___qtablewidgetitem14->setText(QApplication::translate("MainWindow", "13", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem15 = settingsTable->verticalHeaderItem(13);
        ___qtablewidgetitem15->setText(QApplication::translate("MainWindow", "14", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem16 = settingsTable->verticalHeaderItem(14);
        ___qtablewidgetitem16->setText(QApplication::translate("MainWindow", "15", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem17 = settingsTable->verticalHeaderItem(15);
        ___qtablewidgetitem17->setText(QApplication::translate("MainWindow", "16", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem18 = settingsTable->verticalHeaderItem(16);
        ___qtablewidgetitem18->setText(QApplication::translate("MainWindow", "17", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem19 = settingsTable->verticalHeaderItem(17);
        ___qtablewidgetitem19->setText(QApplication::translate("MainWindow", "18", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem20 = settingsTable->verticalHeaderItem(18);
        ___qtablewidgetitem20->setText(QApplication::translate("MainWindow", "19", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem21 = settingsTable->verticalHeaderItem(19);
        ___qtablewidgetitem21->setText(QApplication::translate("MainWindow", "20", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem22 = settingsTable->verticalHeaderItem(20);
        ___qtablewidgetitem22->setText(QApplication::translate("MainWindow", "21", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem23 = settingsTable->verticalHeaderItem(21);
        ___qtablewidgetitem23->setText(QApplication::translate("MainWindow", "22", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem24 = settingsTable->verticalHeaderItem(22);
        ___qtablewidgetitem24->setText(QApplication::translate("MainWindow", "23", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem25 = settingsTable->verticalHeaderItem(23);
        ___qtablewidgetitem25->setText(QApplication::translate("MainWindow", "24", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem26 = settingsTable->verticalHeaderItem(24);
        ___qtablewidgetitem26->setText(QApplication::translate("MainWindow", "25", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem27 = settingsTable->verticalHeaderItem(25);
        ___qtablewidgetitem27->setText(QApplication::translate("MainWindow", "26", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem28 = settingsTable->verticalHeaderItem(26);
        ___qtablewidgetitem28->setText(QApplication::translate("MainWindow", "27", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem29 = settingsTable->verticalHeaderItem(27);
        ___qtablewidgetitem29->setText(QApplication::translate("MainWindow", "28", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem30 = settingsTable->verticalHeaderItem(28);
        ___qtablewidgetitem30->setText(QApplication::translate("MainWindow", "29", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem31 = settingsTable->verticalHeaderItem(29);
        ___qtablewidgetitem31->setText(QApplication::translate("MainWindow", "30", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem32 = settingsTable->verticalHeaderItem(30);
        ___qtablewidgetitem32->setText(QApplication::translate("MainWindow", "31", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem33 = settingsTable->verticalHeaderItem(31);
        ___qtablewidgetitem33->setText(QApplication::translate("MainWindow", "32", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem34 = settingsTable->verticalHeaderItem(32);
        ___qtablewidgetitem34->setText(QApplication::translate("MainWindow", "33", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem35 = settingsTable->verticalHeaderItem(33);
        ___qtablewidgetitem35->setText(QApplication::translate("MainWindow", "34", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem36 = settingsTable->verticalHeaderItem(34);
        ___qtablewidgetitem36->setText(QApplication::translate("MainWindow", "35", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem37 = settingsTable->verticalHeaderItem(35);
        ___qtablewidgetitem37->setText(QApplication::translate("MainWindow", "36", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem38 = settingsTable->verticalHeaderItem(36);
        ___qtablewidgetitem38->setText(QApplication::translate("MainWindow", "37", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem39 = settingsTable->verticalHeaderItem(37);
        ___qtablewidgetitem39->setText(QApplication::translate("MainWindow", "38", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem40 = settingsTable->verticalHeaderItem(38);
        ___qtablewidgetitem40->setText(QApplication::translate("MainWindow", "39", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem41 = settingsTable->verticalHeaderItem(39);
        ___qtablewidgetitem41->setText(QApplication::translate("MainWindow", "40", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tabSettings), QApplication::translate("MainWindow", "Settings", 0, QApplication::UnicodeUTF8));
        btnRefreshRecipeList->setText(QApplication::translate("MainWindow", "Reload Recipes", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem42 = recipeTable->horizontalHeaderItem(0);
        ___qtablewidgetitem42->setText(QApplication::translate("MainWindow", "01", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem43 = recipeTable->horizontalHeaderItem(1);
        ___qtablewidgetitem43->setText(QApplication::translate("MainWindow", "02", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem44 = recipeTable->horizontalHeaderItem(2);
        ___qtablewidgetitem44->setText(QApplication::translate("MainWindow", "03", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem45 = recipeTable->horizontalHeaderItem(3);
        ___qtablewidgetitem45->setText(QApplication::translate("MainWindow", "04", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem46 = recipeTable->verticalHeaderItem(0);
        ___qtablewidgetitem46->setText(QApplication::translate("MainWindow", "01", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem47 = recipeTable->verticalHeaderItem(1);
        ___qtablewidgetitem47->setText(QApplication::translate("MainWindow", "02", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem48 = recipeTable->verticalHeaderItem(2);
        ___qtablewidgetitem48->setText(QApplication::translate("MainWindow", "03", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem49 = recipeTable->verticalHeaderItem(3);
        ___qtablewidgetitem49->setText(QApplication::translate("MainWindow", "04", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem50 = recipeTable->verticalHeaderItem(4);
        ___qtablewidgetitem50->setText(QApplication::translate("MainWindow", "05", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem51 = recipeTable->verticalHeaderItem(5);
        ___qtablewidgetitem51->setText(QApplication::translate("MainWindow", "06", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem52 = recipeTable->verticalHeaderItem(6);
        ___qtablewidgetitem52->setText(QApplication::translate("MainWindow", "07", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem53 = recipeTable->verticalHeaderItem(7);
        ___qtablewidgetitem53->setText(QApplication::translate("MainWindow", "08", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem54 = recipeTable->verticalHeaderItem(8);
        ___qtablewidgetitem54->setText(QApplication::translate("MainWindow", "09", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem55 = recipeTable->verticalHeaderItem(9);
        ___qtablewidgetitem55->setText(QApplication::translate("MainWindow", "10", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem56 = recipeTable->verticalHeaderItem(10);
        ___qtablewidgetitem56->setText(QApplication::translate("MainWindow", "11", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem57 = recipeTable->verticalHeaderItem(11);
        ___qtablewidgetitem57->setText(QApplication::translate("MainWindow", "12", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem58 = recipeTable->verticalHeaderItem(12);
        ___qtablewidgetitem58->setText(QApplication::translate("MainWindow", "13", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem59 = recipeTable->verticalHeaderItem(13);
        ___qtablewidgetitem59->setText(QApplication::translate("MainWindow", "14", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem60 = recipeTable->verticalHeaderItem(14);
        ___qtablewidgetitem60->setText(QApplication::translate("MainWindow", "15", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem61 = recipeTable->verticalHeaderItem(15);
        ___qtablewidgetitem61->setText(QApplication::translate("MainWindow", "16", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem62 = recipeTable->verticalHeaderItem(16);
        ___qtablewidgetitem62->setText(QApplication::translate("MainWindow", "17", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem63 = recipeTable->verticalHeaderItem(17);
        ___qtablewidgetitem63->setText(QApplication::translate("MainWindow", "18", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem64 = recipeTable->verticalHeaderItem(18);
        ___qtablewidgetitem64->setText(QApplication::translate("MainWindow", "19", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem65 = recipeTable->verticalHeaderItem(19);
        ___qtablewidgetitem65->setText(QApplication::translate("MainWindow", "20", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem66 = recipeTable->verticalHeaderItem(20);
        ___qtablewidgetitem66->setText(QApplication::translate("MainWindow", "21", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem67 = recipeTable->verticalHeaderItem(21);
        ___qtablewidgetitem67->setText(QApplication::translate("MainWindow", "22", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem68 = recipeTable->verticalHeaderItem(22);
        ___qtablewidgetitem68->setText(QApplication::translate("MainWindow", "23", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem69 = recipeTable->verticalHeaderItem(23);
        ___qtablewidgetitem69->setText(QApplication::translate("MainWindow", "24", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem70 = recipeTable->verticalHeaderItem(24);
        ___qtablewidgetitem70->setText(QApplication::translate("MainWindow", "25", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem71 = recipeTable->verticalHeaderItem(25);
        ___qtablewidgetitem71->setText(QApplication::translate("MainWindow", "26", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem72 = recipeTable->verticalHeaderItem(26);
        ___qtablewidgetitem72->setText(QApplication::translate("MainWindow", "27", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem73 = recipeTable->verticalHeaderItem(27);
        ___qtablewidgetitem73->setText(QApplication::translate("MainWindow", "28", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem74 = recipeTable->verticalHeaderItem(28);
        ___qtablewidgetitem74->setText(QApplication::translate("MainWindow", "29", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem75 = recipeTable->verticalHeaderItem(29);
        ___qtablewidgetitem75->setText(QApplication::translate("MainWindow", "30", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem76 = recipeTable->verticalHeaderItem(30);
        ___qtablewidgetitem76->setText(QApplication::translate("MainWindow", "31", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem77 = recipeTable->verticalHeaderItem(31);
        ___qtablewidgetitem77->setText(QApplication::translate("MainWindow", "32", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem78 = recipeTable->verticalHeaderItem(32);
        ___qtablewidgetitem78->setText(QApplication::translate("MainWindow", "33", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem79 = recipeTable->verticalHeaderItem(33);
        ___qtablewidgetitem79->setText(QApplication::translate("MainWindow", "34", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem80 = recipeTable->verticalHeaderItem(34);
        ___qtablewidgetitem80->setText(QApplication::translate("MainWindow", "35", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem81 = recipeTable->verticalHeaderItem(35);
        ___qtablewidgetitem81->setText(QApplication::translate("MainWindow", "36", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem82 = recipeTable->verticalHeaderItem(36);
        ___qtablewidgetitem82->setText(QApplication::translate("MainWindow", "37", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem83 = recipeTable->verticalHeaderItem(37);
        ___qtablewidgetitem83->setText(QApplication::translate("MainWindow", "38", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem84 = recipeTable->verticalHeaderItem(38);
        ___qtablewidgetitem84->setText(QApplication::translate("MainWindow", "39", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem85 = recipeTable->verticalHeaderItem(39);
        ___qtablewidgetitem85->setText(QApplication::translate("MainWindow", "40", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem86 = recipeTable->verticalHeaderItem(40);
        ___qtablewidgetitem86->setText(QApplication::translate("MainWindow", "41", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem87 = recipeTable->verticalHeaderItem(41);
        ___qtablewidgetitem87->setText(QApplication::translate("MainWindow", "42", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem88 = recipeTable->verticalHeaderItem(42);
        ___qtablewidgetitem88->setText(QApplication::translate("MainWindow", "43", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem89 = recipeTable->verticalHeaderItem(43);
        ___qtablewidgetitem89->setText(QApplication::translate("MainWindow", "44", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem90 = recipeTable->verticalHeaderItem(44);
        ___qtablewidgetitem90->setText(QApplication::translate("MainWindow", "45", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem91 = recipeTable->verticalHeaderItem(45);
        ___qtablewidgetitem91->setText(QApplication::translate("MainWindow", "46", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem92 = recipeTable->verticalHeaderItem(46);
        ___qtablewidgetitem92->setText(QApplication::translate("MainWindow", "47", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem93 = recipeTable->verticalHeaderItem(47);
        ___qtablewidgetitem93->setText(QApplication::translate("MainWindow", "48", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem94 = recipeTable->verticalHeaderItem(48);
        ___qtablewidgetitem94->setText(QApplication::translate("MainWindow", "49", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem95 = recipeTable->verticalHeaderItem(49);
        ___qtablewidgetitem95->setText(QApplication::translate("MainWindow", "50", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tabRecipe), QApplication::translate("MainWindow", "Recipe", 0, QApplication::UnicodeUTF8));
        chkDIN_03->setText(QApplication::translate("MainWindow", "SI_03", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("MainWindow", "I 03", 0, QApplication::UnicodeUTF8));
        lblDIN_03->setText(QApplication::translate("MainWindow", "I_03", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("MainWindow", "Q 03", 0, QApplication::UnicodeUTF8));
        lblDOUT_03->setText(QApplication::translate("MainWindow", "Q_03", 0, QApplication::UnicodeUTF8));
        chkDIN_04->setText(QApplication::translate("MainWindow", "SI_04", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("MainWindow", "I 04", 0, QApplication::UnicodeUTF8));
        lblDIN_04->setText(QApplication::translate("MainWindow", "I_04", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("MainWindow", "Q 04", 0, QApplication::UnicodeUTF8));
        lblDOUT_04->setText(QApplication::translate("MainWindow", "Q_04", 0, QApplication::UnicodeUTF8));
        chkDIN_01->setText(QApplication::translate("MainWindow", "SI_01", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("MainWindow", "I 01", 0, QApplication::UnicodeUTF8));
        lblDIN_01->setText(QApplication::translate("MainWindow", "I_01", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("MainWindow", "Q 01", 0, QApplication::UnicodeUTF8));
        lblDOUT_01->setText(QApplication::translate("MainWindow", "Q_01", 0, QApplication::UnicodeUTF8));
        chkDIN_02->setText(QApplication::translate("MainWindow", "SI_02", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("MainWindow", "I 02", 0, QApplication::UnicodeUTF8));
        lblDIN_02->setText(QApplication::translate("MainWindow", "I_02", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("MainWindow", "Q 02", 0, QApplication::UnicodeUTF8));
        lblDOUT_02->setText(QApplication::translate("MainWindow", "Q_02", 0, QApplication::UnicodeUTF8));
        btnCalibrateZERO->setText(QApplication::translate("MainWindow", "Calibrate ZERO", 0, QApplication::UnicodeUTF8));
        btnCalibrateWEIGHT->setText(QApplication::translate("MainWindow", "Calibrate WEIGHT", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("MainWindow", "Calibration weight:", 0, QApplication::UnicodeUTF8));
        chkWriteToLoadcell->setText(QApplication::translate("MainWindow", "Activate", 0, QApplication::UnicodeUTF8));
        chkDebugWriteToFile->setText(QApplication::translate("MainWindow", "Debug", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tabDio), QApplication::translate("MainWindow", "Service", 0, QApplication::UnicodeUTF8));
        lblSystemState->setText(QApplication::translate("MainWindow", "System state", 0, QApplication::UnicodeUTF8));
        lblCountDown->setText(QApplication::translate("MainWindow", "Counter", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
